In [1]:
import numpy as np


In [2]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,0,0,1]]).T
X.shape ,Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    # print(type(z))
    # print("z printed milord")
    return 1/(1+np.exp(-1*z))
  

In [4]:
def dsig(z):
    return sig(z)*(1-sig(z))

In [5]:
weights=2*np.random.random((2,1)) - 1
bias=2*np.random.random(1)-1
print(weights,bias)

[[-0.93262039]
 [ 0.33771813]] [0.54939697]


In [6]:

output0=X
output=sig(np.dot(output0,weights)+bias)
print(output)

[[0.63399567]
 [0.70829447]
 [0.40534968]
 [0.48862564]]


In [7]:
# this is difft wid hidden layer only forward propagation
wh=2*np.random.random((2,2))-1
bh=2*np.random.random((1,2)) -1
bo=2*np.random.random((1,1))-1
lr=0.1
wo=2*np.random.random((2,1)) -1
#print(wh)


In [8]:
#extension of above
output0=X
outputH=sig(np.dot(output0,wh) + bh)
outputf=sig(np.dot(outputH,wo)+bo)
print(outputf)

[[0.42877583]
 [0.3972471 ]
 [0.49003354]
 [0.45787564]]


In [13]:
#neural network implementation without hidden layer wid back propagation but no hidden later
# how more dumb can i be
for _ in range(10000):
    output0=X
    output=sig(np.dot(output0,weights)+bias)
    changes=np.array([[0.0],[0.0]])
    first_term=output - Y
    second_term=dsig(np.dot(output0,weights)+bias)
    first_two=first_term*second_term
    # print(first_two)
    for i in range(4):
        for j in range(2):
            changes[j][0] += first_two[i][0]*output0[i][j]

    weights=weights-lr*changes
    bias_change=0.0
    for i in range(4):
        for j in range(2):
            bias_change+= first_two[i][0]*1

    bias=bias-lr*bias_change

print(sig(np.dot(X,weights)+bias))


    


[[1.21004680e-04]
 [4.36079470e-02]
 [4.36079679e-02]
 [9.44992309e-01]]


In [15]:
# doing this without for loops while multiplying
for _ in range(100000):
    output0=X
    output=sig(np.dot(output0,weights)+bias)
    changes=np.array([[0.0],[0.0]])
    first_term=output - Y
    second_term=dsig(np.dot(output0,weights)+bias)
    first_two=first_term*second_term
    # print(first_two)
    changes=np.dot(output0.T,first_two)
    # for i in range(4):
    #     for j in range(2):
    #         changes[j][0] += first_two[i][0]*output0[i][j]

    weights=weights-lr*changes
    bias_change=0.0
    bias_change=np.sum(first_two)
    # for i in range(4):
    #     for j in range(2):
    #         bias_change+= first_two[i][0]*1

    bias=bias-lr*bias_change

print(sig(np.dot(X,weights)+bias))

[[2.61870876e-06]
 [1.28487681e-02]
 [1.28487681e-02]
 [9.84778022e-01]]
